// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8xwIKf5iwuqhX1NdXVPewVs9Zk1gsJWE',
    appId: '1:159105612270:web:ec229572db4c20a7e9f6ff',
    messagingSenderId: '159105612270',
    projectId: 'run-app-a881b',
    authDomain: 'run-app-a881b.firebaseapp.com',
    storageBucket: 'run-app-a881b.appspot.com',
    measurementId: 'G-S4GD828JM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ2WNdUO4AIbKIxQ90XGfAZ_QPn-6LJqE',
    appId: '1:159105612270:android:91fce5c79439718ee9f6ff',
    messagingSenderId: '159105612270',
    projectId: 'run-app-a881b',
    storageBucket: 'run-app-a881b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo513AYSjnzo--w_uvRmQlnxa6r7RgIc8',
    appId: '1:159105612270:ios:8f16c52826637fa7e9f6ff',
    messagingSenderId: '159105612270',
    projectId: 'run-app-a881b',
    storageBucket: 'run-app-a881b.appspot.com',
    iosBundleId: 'com.example.runningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo513AYSjnzo--w_uvRmQlnxa6r7RgIc8',
    appId: '1:159105612270:ios:250fdc7b04b01702e9f6ff',
    messagingSenderId: '159105612270',
    projectId: 'run-app-a881b',
    storageBucket: 'run-app-a881b.appspot.com',
    iosBundleId: 'com.example.runningApp.RunnerTests',
  );
}
